// scripts/helpers.js
const fs = require("fs");
const path = require("path");

function saveFrontendFiles(addresses) {
  const contractsDir = path.join(__dirname, "..", "src", "abi");
  if (!fs.existsSync(contractsDir)) {
    fs.mkdirSync(contractsDir, { recursive: true });
  }

  // Save addresses list
  fs.writeFileSync(
    path.join(contractsDir, "contract-addresses.json"),
    JSON.stringify(addresses, undefined, 2)
  );

  // Save ABIs generated by Hardhat (from artifacts)
  const artifactsDir = path.join(__dirname, "..", "artifacts", "contracts");
  const mappingPath = path.join(artifactsDir, "PhoneMapping.sol", "PhoneMapping.json");
  const paymentPath = path.join(artifactsDir, "PaymentContract.sol", "PaymentContract.json");

  if (fs.existsSync(mappingPath)) {
    fs.copyFileSync(mappingPath, path.join(contractsDir, "PhoneMapping.json"));
  }

  if (fs.existsSync(paymentPath)) {
    fs.copyFileSync(paymentPath, path.join(contractsDir, "PaymentContract.json"));
  }

  console.log("Frontend files saved to src/abi/");
}

module.exports = { saveFrontendFiles };
